package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Callerid generated by hbm2java
 */
@Entity
@Table(name = "callerid", schema = "public")
public class Callerid implements java.io.Serializable {

	private long id;
	private Estacioncentral estacioncentral;
	private String numero;

	public Callerid() {
	}

	public Callerid(long id) {
		this.id = id;
	}

	public Callerid(long id, Estacioncentral estacioncentral, String numero) {
		this.id = id;
		this.estacioncentral = estacioncentral;
		this.numero = numero;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestacioncentral")
	public Estacioncentral getEstacioncentral() {
		return this.estacioncentral;
	}

	public void setEstacioncentral(Estacioncentral estacioncentral) {
		this.estacioncentral = estacioncentral;
	}

	@Column(name = "numero", length = 10)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

}
