package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", schema = "public")
public class Categoria implements java.io.Serializable {

	private long id;
	private Protocolocomunicacion protocolocomunicacion;
	private String descripcion;
	private Integer prioridad;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public Categoria() {
	}

	public Categoria(long id) {
		this.id = id;
	}

	public Categoria(long id, Protocolocomunicacion protocolocomunicacion,
			String descripcion, Integer prioridad, Set<Evento> eventos) {
		this.id = id;
		this.protocolocomunicacion = protocolocomunicacion;
		this.descripcion = descripcion;
		this.prioridad = prioridad;
		this.eventos = eventos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprotocolocomunicacion")
	public Protocolocomunicacion getProtocolocomunicacion() {
		return this.protocolocomunicacion;
	}

	public void setProtocolocomunicacion(
			Protocolocomunicacion protocolocomunicacion) {
		this.protocolocomunicacion = protocolocomunicacion;
	}

	@Column(name = "descripcion", length = 30)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "prioridad")
	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
