package com.tcustodia.domain;

// Generated 18/07/2015 02:38:18 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "ciudad", schema = "public")
public class Ciudad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9177124075621267399L;
	private long id;
	private String nombre;
	private Set<Sector> sectors = new HashSet<Sector>(0);

	public Ciudad() {
	}

	public Ciudad(long id) {
		this.id = id;
	}

	public Ciudad(long id, String nombre, Set<Sector> sectors) {
		this.id = id;
		this.nombre = nombre;
		this.sectors = sectors;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<Sector> getSectors() {
		return this.sectors;
	}

	public void setSectors(Set<Sector> sectors) {
		this.sectors = sectors;
	}

}
