package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contactozona generated by hbm2java
 */
@Entity
@Table(name = "contactozona", schema = "public")
public class Contactozona implements java.io.Serializable {

	private long id;
	private Contactos contactos;
	private Zona zona;

	public Contactozona() {
	}

	public Contactozona(long id) {
		this.id = id;
	}

	public Contactozona(long id, Contactos contactos, Zona zona) {
		this.id = id;
		this.contactos = contactos;
		this.zona = zona;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcontacto")
	public Contactos getContactos() {
		return this.contactos;
	}

	public void setContactos(Contactos contactos) {
		this.contactos = contactos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idzona")
	public Zona getZona() {
		return this.zona;
	}

	public void setZona(Zona zona) {
		this.zona = zona;
	}

}
