package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuerposeguridadsector generated by hbm2java
 */
@Entity
@Table(name = "cuerposeguridadsector", schema = "public")
public class Cuerposeguridadsector implements java.io.Serializable {

	private long id;
	private Cuerposeguridad cuerposeguridad;
	private Sector sector;
	private Long idsector;
	private String direccion;
	private String comentario;
	private Character coordenada;
	private Set<Telefonocuerposeguridad> telefonocuerposeguridads = new HashSet<Telefonocuerposeguridad>(
			0);

	public Cuerposeguridadsector() {
	}

	public Cuerposeguridadsector(long id) {
		this.id = id;
	}

	public Cuerposeguridadsector(long id, Cuerposeguridad cuerposeguridad,
			Sector sector, Long idsector, String direccion, String comentario,
			Character coordenada,
			Set<Telefonocuerposeguridad> telefonocuerposeguridads) {
		this.id = id;
		this.cuerposeguridad = cuerposeguridad;
		this.sector = sector;
		this.idsector = idsector;
		this.direccion = direccion;
		this.comentario = comentario;
		this.coordenada = coordenada;
		this.telefonocuerposeguridads = telefonocuerposeguridads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcuerposeguridad")
	public Cuerposeguridad getCuerposeguridad() {
		return this.cuerposeguridad;
	}

	public void setCuerposeguridad(Cuerposeguridad cuerposeguridad) {
		this.cuerposeguridad = cuerposeguridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcuerposeguridad", insertable = false, updatable = false)
	public Sector getSector() {
		return this.sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	@Column(name = "idsector")
	public Long getIdsector() {
		return this.idsector;
	}

	public void setIdsector(Long idsector) {
		this.idsector = idsector;
	}

	@Column(name = "direccion", length = 300)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "comentario", length = 300)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "coordenada", length = 1)
	public Character getCoordenada() {
		return this.coordenada;
	}

	public void setCoordenada(Character coordenada) {
		this.coordenada = coordenada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuerposeguridadsector")
	public Set<Telefonocuerposeguridad> getTelefonocuerposeguridads() {
		return this.telefonocuerposeguridads;
	}

	public void setTelefonocuerposeguridads(
			Set<Telefonocuerposeguridad> telefonocuerposeguridads) {
		this.telefonocuerposeguridads = telefonocuerposeguridads;
	}

}
