package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipo generated by hbm2java
 */
@Entity
@Table(name = "equipo", schema = "public")
public class Equipo implements java.io.Serializable {

	private long id;
	private String nombre;
	private String modelo;
	private String marca;
	private String versioninstalada;
	private Set<Equipozona> equipozonas = new HashSet<Equipozona>(0);

	public Equipo() {
	}

	public Equipo(long id) {
		this.id = id;
	}

	public Equipo(long id, String nombre, String modelo, String marca,
			String versioninstalada, Set<Equipozona> equipozonas) {
		this.id = id;
		this.nombre = nombre;
		this.modelo = modelo;
		this.marca = marca;
		this.versioninstalada = versioninstalada;
		this.equipozonas = equipozonas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "modelo", length = 100)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "marca", length = 100)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "versioninstalada", length = 100)
	public String getVersioninstalada() {
		return this.versioninstalada;
	}

	public void setVersioninstalada(String versioninstalada) {
		this.versioninstalada = versioninstalada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipo")
	public Set<Equipozona> getEquipozonas() {
		return this.equipozonas;
	}

	public void setEquipozonas(Set<Equipozona> equipozonas) {
		this.equipozonas = equipozonas;
	}

}
