package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "evento", schema = "public")
public class Evento implements java.io.Serializable {

	private long id;
	private Categoria categoria;
	private Cuerposeguridad cuerposeguridad;
	private Long ideventorestauracion;
	private Integer tiemporestauracion;
	private String descripcion;
	private Boolean llamar;
	private Boolean visible;
	private Set<Zonaevento> zonaeventos = new HashSet<Zonaevento>(0);
	private Set<Senal> senals = new HashSet<Senal>(0);

	public Evento() {
	}

	public Evento(long id) {
		this.id = id;
	}

	public Evento(long id, Categoria categoria,
			Cuerposeguridad cuerposeguridad, Long ideventorestauracion,
			Integer tiemporestauracion, String descripcion, Boolean llamar,
			Boolean visible, Set<Zonaevento> zonaeventos, Set<Senal> senals) {
		this.id = id;
		this.categoria = categoria;
		this.cuerposeguridad = cuerposeguridad;
		this.ideventorestauracion = ideventorestauracion;
		this.tiemporestauracion = tiemporestauracion;
		this.descripcion = descripcion;
		this.llamar = llamar;
		this.visible = visible;
		this.zonaeventos = zonaeventos;
		this.senals = senals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoria")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcuerposeguridad")
	public Cuerposeguridad getCuerposeguridad() {
		return this.cuerposeguridad;
	}

	public void setCuerposeguridad(Cuerposeguridad cuerposeguridad) {
		this.cuerposeguridad = cuerposeguridad;
	}

	@Column(name = "ideventorestauracion")
	public Long getIdeventorestauracion() {
		return this.ideventorestauracion;
	}

	public void setIdeventorestauracion(Long ideventorestauracion) {
		this.ideventorestauracion = ideventorestauracion;
	}

	@Column(name = "tiemporestauracion")
	public Integer getTiemporestauracion() {
		return this.tiemporestauracion;
	}

	public void setTiemporestauracion(Integer tiemporestauracion) {
		this.tiemporestauracion = tiemporestauracion;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "llamar")
	public Boolean getLlamar() {
		return this.llamar;
	}

	public void setLlamar(Boolean llamar) {
		this.llamar = llamar;
	}

	@Column(name = "visible")
	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evento")
	public Set<Zonaevento> getZonaeventos() {
		return this.zonaeventos;
	}

	public void setZonaeventos(Set<Zonaevento> zonaeventos) {
		this.zonaeventos = zonaeventos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evento")
	public Set<Senal> getSenals() {
		return this.senals;
	}

	public void setSenals(Set<Senal> senals) {
		this.senals = senals;
	}

}
