package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupoalarma generated by hbm2java
 */
@Entity
@Table(name = "grupoalarma", schema = "public")
public class Grupoalarma implements java.io.Serializable {

	private long id;
	private String descripcion;
	private Set<Estacioncentral> estacioncentrals = new HashSet<Estacioncentral>(
			0);

	public Grupoalarma() {
	}

	public Grupoalarma(long id) {
		this.id = id;
	}

	public Grupoalarma(long id, String descripcion,
			Set<Estacioncentral> estacioncentrals) {
		this.id = id;
		this.descripcion = descripcion;
		this.estacioncentrals = estacioncentrals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoalarma")
	public Set<Estacioncentral> getEstacioncentrals() {
		return this.estacioncentrals;
	}

	public void setEstacioncentrals(Set<Estacioncentral> estacioncentrals) {
		this.estacioncentrals = estacioncentrals;
	}

}
