package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Informacionmedica generated by hbm2java
 */
@Entity
@Table(name = "informacionmedica", schema = "public")
public class Informacionmedica implements java.io.Serializable {

	private long id;
	private Persona persona;
	private Estacioncentral estacioncentral;
	private Long iddoctor;
	private String alergias;
	private String medicamentos;
	private String tiposangre;
	private String infomedico;
	private String observaciones;
	private Boolean discapacitado;
	private Boolean solo;

	public Informacionmedica() {
	}

	public Informacionmedica(long id) {
		this.id = id;
	}

	public Informacionmedica(long id, Persona persona,
			Estacioncentral estacioncentral, Long iddoctor, String alergias,
			String medicamentos, String tiposangre, String infomedico,
			String observaciones, Boolean discapacitado, Boolean solo) {
		this.id = id;
		this.persona = persona;
		this.estacioncentral = estacioncentral;
		this.iddoctor = iddoctor;
		this.alergias = alergias;
		this.medicamentos = medicamentos;
		this.tiposangre = tiposangre;
		this.infomedico = infomedico;
		this.observaciones = observaciones;
		this.discapacitado = discapacitado;
		this.solo = solo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestacioncentral")
	public Estacioncentral getEstacioncentral() {
		return this.estacioncentral;
	}

	public void setEstacioncentral(Estacioncentral estacioncentral) {
		this.estacioncentral = estacioncentral;
	}

	@Column(name = "iddoctor")
	public Long getIddoctor() {
		return this.iddoctor;
	}

	public void setIddoctor(Long iddoctor) {
		this.iddoctor = iddoctor;
	}

	@Column(name = "alergias", length = 300)
	public String getAlergias() {
		return this.alergias;
	}

	public void setAlergias(String alergias) {
		this.alergias = alergias;
	}

	@Column(name = "medicamentos", length = 300)
	public String getMedicamentos() {
		return this.medicamentos;
	}

	public void setMedicamentos(String medicamentos) {
		this.medicamentos = medicamentos;
	}

	@Column(name = "tiposangre", length = 10)
	public String getTiposangre() {
		return this.tiposangre;
	}

	public void setTiposangre(String tiposangre) {
		this.tiposangre = tiposangre;
	}

	@Column(name = "infomedico", length = 300)
	public String getInfomedico() {
		return this.infomedico;
	}

	public void setInfomedico(String infomedico) {
		this.infomedico = infomedico;
	}

	@Column(name = "observaciones", length = 300)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "discapacitado")
	public Boolean getDiscapacitado() {
		return this.discapacitado;
	}

	public void setDiscapacitado(Boolean discapacitado) {
		this.discapacitado = discapacitado;
	}

	@Column(name = "solo")
	public Boolean getSolo() {
		return this.solo;
	}

	public void setSolo(Boolean solo) {
		this.solo = solo;
	}

}
