package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Llamada generated by hbm2java
 */
@Entity
@Table(name = "llamada", schema = "public")
public class Llamada implements java.io.Serializable {

	private long id;
	private Senal senal;
	private Long idtelefono;
	private Date horainicio;
	private Date horafin;
	private String comentariooperador;

	public Llamada() {
	}

	public Llamada(long id) {
		this.id = id;
	}

	public Llamada(long id, Senal senal, Long idtelefono, Date horainicio,
			Date horafin, String comentariooperador) {
		this.id = id;
		this.senal = senal;
		this.idtelefono = idtelefono;
		this.horainicio = horainicio;
		this.horafin = horafin;
		this.comentariooperador = comentariooperador;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsenal")
	public Senal getSenal() {
		return this.senal;
	}

	public void setSenal(Senal senal) {
		this.senal = senal;
	}

	@Column(name = "idtelefono")
	public Long getIdtelefono() {
		return this.idtelefono;
	}

	public void setIdtelefono(Long idtelefono) {
		this.idtelefono = idtelefono;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "horainicio", length = 13)
	public Date getHorainicio() {
		return this.horainicio;
	}

	public void setHorainicio(Date horainicio) {
		this.horainicio = horainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "horafin", length = 13)
	public Date getHorafin() {
		return this.horafin;
	}

	public void setHorafin(Date horafin) {
		this.horafin = horafin;
	}

	@Column(name = "comentariooperador", length = 300)
	public String getComentariooperador() {
		return this.comentariooperador;
	}

	public void setComentariooperador(String comentariooperador) {
		this.comentariooperador = comentariooperador;
	}

}
