package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name = "mensaje", schema = "public")
public class Mensaje implements java.io.Serializable {

	private long id;
	private String mensaje;
	private String callerid;
	private Date fecha;
	private Set<Senal> senals = new HashSet<Senal>(0);

	public Mensaje() {
	}

	public Mensaje(long id) {
		this.id = id;
	}

	public Mensaje(long id, String mensaje, String callerid, Date fecha,
			Set<Senal> senals) {
		this.id = id;
		this.mensaje = mensaje;
		this.callerid = callerid;
		this.fecha = fecha;
		this.senals = senals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "mensaje", length = 100)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@Column(name = "callerid", length = 10)
	public String getCallerid() {
		return this.callerid;
	}

	public void setCallerid(String callerid) {
		this.callerid = callerid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mensaje")
	public Set<Senal> getSenals() {
		return this.senals;
	}

	public void setSenals(Set<Senal> senals) {
		this.senals = senals;
	}

}
