package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operador generated by hbm2java
 */
@Entity
@Table(name = "operador", schema = "public")
public class Operador implements java.io.Serializable {

	private long id;
	private String login;
	private String password;
	private String nombre;
	private String apellido;
	private Set<Senal> senals = new HashSet<Senal>(0);

	public Operador() {
	}

	public Operador(long id) {
		this.id = id;
	}

	public Operador(long id, String login, String password, String nombre,
			String apellido, Set<Senal> senals) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.nombre = nombre;
		this.apellido = apellido;
		this.senals = senals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "login", length = 30)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 30)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operador")
	public Set<Senal> getSenals() {
		return this.senals;
	}

	public void setSenals(Set<Senal> senals) {
		this.senals = senals;
	}

}
