package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parentesco generated by hbm2java
 */
@Entity
@Table(name = "parentesco", schema = "public")
public class Parentesco implements java.io.Serializable {

	private long id;
	private String descripcion;
	private Set<Contactos> contactoses = new HashSet<Contactos>(0);

	public Parentesco() {
	}

	public Parentesco(long id) {
		this.id = id;
	}

	public Parentesco(long id, String descripcion, Set<Contactos> contactoses) {
		this.id = id;
		this.descripcion = descripcion;
		this.contactoses = contactoses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentesco")
	public Set<Contactos> getContactoses() {
		return this.contactoses;
	}

	public void setContactoses(Set<Contactos> contactoses) {
		this.contactoses = contactoses;
	}

}
