package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Particion generated by hbm2java
 */
@Entity
@Table(name = "particion", schema = "public")
public class Particion implements java.io.Serializable {

	private long id;
	private Estacioncentral estacioncentral;
	private String numero;
	private String descripcion;
	private Set<Zona> zonas = new HashSet<Zona>(0);

	public Particion() {
	}

	public Particion(long id) {
		this.id = id;
	}

	public Particion(long id, Estacioncentral estacioncentral, String numero,
			String descripcion, Set<Zona> zonas) {
		this.id = id;
		this.estacioncentral = estacioncentral;
		this.numero = numero;
		this.descripcion = descripcion;
		this.zonas = zonas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestacioncentral")
	public Estacioncentral getEstacioncentral() {
		return this.estacioncentral;
	}

	public void setEstacioncentral(Estacioncentral estacioncentral) {
		this.estacioncentral = estacioncentral;
	}

	@Column(name = "numero", length = 4)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "descripcion", length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "particion")
	public Set<Zona> getZonas() {
		return this.zonas;
	}

	public void setZonas(Set<Zona> zonas) {
		this.zonas = zonas;
	}

}
