package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "public")
public class Persona implements java.io.Serializable {

	private long id;
	private Tipopersona tipopersona;
	private Direccion direccion;
	private String nombre;
	private String apellido;
	private String sexo;
	private Date fechanacimiento;
	private Set<Informacionmedica> informacionmedicas = new HashSet<Informacionmedica>(
			0);
	private Set<Estacioncentral> estacioncentrals = new HashSet<Estacioncentral>(
			0);
	private Set<Telefono> telefonos = new HashSet<Telefono>(0);
	private Set<Contactos> contactoses = new HashSet<Contactos>(0);

	public Persona() {
	}

	public Persona(long id, Tipopersona tipopersona, String nombre,
			String apellido, String sexo, Date fechanacimiento) {
		this.id = id;
		this.tipopersona = tipopersona;
		this.nombre = nombre;
		this.apellido = apellido;
		this.sexo = sexo;
		this.fechanacimiento = fechanacimiento;
	}

	public Persona(long id, Tipopersona tipopersona, Direccion direccion,
			String nombre, String apellido, String sexo, Date fechanacimiento,
			Set<Informacionmedica> informacionmedicas,
			Set<Estacioncentral> estacioncentrals, Set<Telefono> telefonos,
			Set<Contactos> contactoses) {
		this.id = id;
		this.tipopersona = tipopersona;
		this.direccion = direccion;
		this.nombre = nombre;
		this.apellido = apellido;
		this.sexo = sexo;
		this.fechanacimiento = fechanacimiento;
		this.informacionmedicas = informacionmedicas;
		this.estacioncentrals = estacioncentrals;
		this.telefonos = telefonos;
		this.contactoses = contactoses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipopersona", nullable = false)
	public Tipopersona getTipopersona() {
		return this.tipopersona;
	}

	public void setTipopersona(Tipopersona tipopersona) {
		this.tipopersona = tipopersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddireccion")
	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false, length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "sexo", nullable = false, length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechanacimiento", nullable = false, length = 13)
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Informacionmedica> getInformacionmedicas() {
		return this.informacionmedicas;
	}

	public void setInformacionmedicas(Set<Informacionmedica> informacionmedicas) {
		this.informacionmedicas = informacionmedicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Estacioncentral> getEstacioncentrals() {
		return this.estacioncentrals;
	}

	public void setEstacioncentrals(Set<Estacioncentral> estacioncentrals) {
		this.estacioncentrals = estacioncentrals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Telefono> getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos(Set<Telefono> telefonos) {
		this.telefonos = telefonos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Contactos> getContactoses() {
		return this.contactoses;
	}

	public void setContactoses(Set<Contactos> contactoses) {
		this.contactoses = contactoses;
	}

}
