package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Protocolocomunicacion generated by hbm2java
 */
@Entity
@Table(name = "protocolocomunicacion", schema = "public")
public class Protocolocomunicacion implements java.io.Serializable {

	private long id;
	private String descripcion;
	private Set<Estacioncentral> estacioncentrals = new HashSet<Estacioncentral>(
			0);
	private Set<Categoria> categorias = new HashSet<Categoria>(0);

	public Protocolocomunicacion() {
	}

	public Protocolocomunicacion(long id) {
		this.id = id;
	}

	public Protocolocomunicacion(long id, String descripcion,
			Set<Estacioncentral> estacioncentrals, Set<Categoria> categorias) {
		this.id = id;
		this.descripcion = descripcion;
		this.estacioncentrals = estacioncentrals;
		this.categorias = categorias;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion", length = 30)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "protocolocomunicacion")
	public Set<Estacioncentral> getEstacioncentrals() {
		return this.estacioncentrals;
	}

	public void setEstacioncentrals(Set<Estacioncentral> estacioncentrals) {
		this.estacioncentrals = estacioncentrals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "protocolocomunicacion")
	public Set<Categoria> getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Set<Categoria> categorias) {
		this.categorias = categorias;
	}

}
