package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resolucion generated by hbm2java
 */
@Entity
@Table(name = "resolucion", schema = "public")
public class Resolucion implements java.io.Serializable {

	private long id;
	private Long codigo;
	private String descripcion;
	private Set<Senal> senals = new HashSet<Senal>(0);

	public Resolucion() {
	}

	public Resolucion(long id) {
		this.id = id;
	}

	public Resolucion(long id, Long codigo, String descripcion,
			Set<Senal> senals) {
		this.id = id;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.senals = senals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "codigo")
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 30)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resolucion")
	public Set<Senal> getSenals() {
		return this.senals;
	}

	public void setSenals(Set<Senal> senals) {
		this.senals = senals;
	}

}
