package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Senal generated by hbm2java
 */
@Entity
@Table(name = "senal", schema = "public")
public class Senal implements java.io.Serializable {

	private long id;
	private Mensaje mensaje;
	private Evento evento;
	private Zona zona;
	private Operador operador;
	private Resolucion resolucion;
	private String notaoperador;
	private String abonado;
	private Character evento_1;
	private Date fecha;
	private Set<Llamada> llamadas = new HashSet<Llamada>(0);

	public Senal() {
	}

	public Senal(long id) {
		this.id = id;
	}

	public Senal(long id, Mensaje mensaje, Evento evento, Zona zona,
			Operador operador, Resolucion resolucion, String notaoperador,
			String abonado, Character evento_1, Date fecha,
			Set<Llamada> llamadas) {
		this.id = id;
		this.mensaje = mensaje;
		this.evento = evento;
		this.zona = zona;
		this.operador = operador;
		this.resolucion = resolucion;
		this.notaoperador = notaoperador;
		this.abonado = abonado;
		this.evento_1 = evento_1;
		this.fecha = fecha;
		this.llamadas = llamadas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmensaje")
	public Mensaje getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(Mensaje mensaje) {
		this.mensaje = mensaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idevento")
	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idzona")
	public Zona getZona() {
		return this.zona;
	}

	public void setZona(Zona zona) {
		this.zona = zona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idoperador")
	public Operador getOperador() {
		return this.operador;
	}

	public void setOperador(Operador operador) {
		this.operador = operador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idresolucion")
	public Resolucion getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(Resolucion resolucion) {
		this.resolucion = resolucion;
	}

	@Column(name = "notaoperador", length = 300)
	public String getNotaoperador() {
		return this.notaoperador;
	}

	public void setNotaoperador(String notaoperador) {
		this.notaoperador = notaoperador;
	}

	@Column(name = "abonado", length = 10)
	public String getAbonado() {
		return this.abonado;
	}

	public void setAbonado(String abonado) {
		this.abonado = abonado;
	}

	@Column(name = "evento", length = 1)
	public Character getEvento_1() {
		return this.evento_1;
	}

	public void setEvento_1(Character evento_1) {
		this.evento_1 = evento_1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "senal")
	public Set<Llamada> getLlamadas() {
		return this.llamadas;
	}

	public void setLlamadas(Set<Llamada> llamadas) {
		this.llamadas = llamadas;
	}

}
