package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name = "telefono", schema = "public")
public class Telefono implements java.io.Serializable {

	private long id;
	private Tipotelefono tipotelefono;
	private Persona persona;
	private String numero;
	private String extension;
	private Integer orden;

	public Telefono() {
	}

	public Telefono(long id) {
		this.id = id;
	}

	public Telefono(long id, Tipotelefono tipotelefono, Persona persona,
			String numero, String extension, Integer orden) {
		this.id = id;
		this.tipotelefono = tipotelefono;
		this.persona = persona;
		this.numero = numero;
		this.extension = extension;
		this.orden = orden;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipotelefono")
	public Tipotelefono getTipotelefono() {
		return this.tipotelefono;
	}

	public void setTipotelefono(Tipotelefono tipotelefono) {
		this.tipotelefono = tipotelefono;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "numero", length = 25)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "extension", length = 4)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

}
