package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefonocuerposeguridad generated by hbm2java
 */
@Entity
@Table(name = "telefonocuerposeguridad", schema = "public")
public class Telefonocuerposeguridad implements java.io.Serializable {

	private long id;
	private Cuerposeguridadsector cuerposeguridadsector;
	private String numero;
	private String extension;
	private Integer orden;

	public Telefonocuerposeguridad() {
	}

	public Telefonocuerposeguridad(long id) {
		this.id = id;
	}

	public Telefonocuerposeguridad(long id,
			Cuerposeguridadsector cuerposeguridadsector, String numero,
			String extension, Integer orden) {
		this.id = id;
		this.cuerposeguridadsector = cuerposeguridadsector;
		this.numero = numero;
		this.extension = extension;
		this.orden = orden;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcuerposeguridad")
	public Cuerposeguridadsector getCuerposeguridadsector() {
		return this.cuerposeguridadsector;
	}

	public void setCuerposeguridadsector(
			Cuerposeguridadsector cuerposeguridadsector) {
		this.cuerposeguridadsector = cuerposeguridadsector;
	}

	@Column(name = "numero", length = 20)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "extension", length = 4)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

}
