package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipopersona generated by hbm2java
 */
@Entity
@Table(name = "tipopersona", schema = "public")
public class Tipopersona implements java.io.Serializable {

	private long id;
	private String descripcion;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Tipopersona() {
	}

	public Tipopersona(long id) {
		this.id = id;
	}

	public Tipopersona(long id, String descripcion, Set<Persona> personas) {
		this.id = id;
		this.descripcion = descripcion;
		this.personas = personas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipopersona")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
