package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipotelefono generated by hbm2java
 */
@Entity
@Table(name = "tipotelefono", schema = "public")
public class Tipotelefono implements java.io.Serializable {

	private long id;
	private Long descripcion;
	private Set<Telefono> telefonos = new HashSet<Telefono>(0);

	public Tipotelefono() {
	}

	public Tipotelefono(long id) {
		this.id = id;
	}

	public Tipotelefono(long id, Long descripcion, Set<Telefono> telefonos) {
		this.id = id;
		this.descripcion = descripcion;
		this.telefonos = telefonos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public Long getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(Long descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipotelefono")
	public Set<Telefono> getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos(Set<Telefono> telefonos) {
		this.telefonos = telefonos;
	}

}
