package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipodireccion generated by hbm2java
 */
@Entity
@Table(name = "tipodireccion", schema = "public")
public class Tipodireccion implements java.io.Serializable {

	private long id;
	private String descripcion;
	private Integer orden;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);

	public Tipodireccion() {
	}

	public Tipodireccion(long id) {
		this.id = id;
	}

	public Tipodireccion(long id, String descripcion, Integer orden,
			Set<Direccion> direccions) {
		this.id = id;
		this.descripcion = descripcion;
		this.orden = orden;
		this.direccions = direccions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipodireccion")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

}
