package com.tcustodia.domain;

// Generated 18/07/2015 03:56:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Zonaevento generated by hbm2java
 */
@Entity
@Table(name = "zonaevento", schema = "public")
public class Zonaevento implements java.io.Serializable {

	private long id;
	private Evento evento;
	private Zona zona;
	private Integer tiemporestauracion;
	private Boolean llamar;
	private Boolean visitble;

	public Zonaevento() {
	}

	public Zonaevento(long id) {
		this.id = id;
	}

	public Zonaevento(long id, Evento evento, Zona zona,
			Integer tiemporestauracion, Boolean llamar, Boolean visitble) {
		this.id = id;
		this.evento = evento;
		this.zona = zona;
		this.tiemporestauracion = tiemporestauracion;
		this.llamar = llamar;
		this.visitble = visitble;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idevento")
	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idzona")
	public Zona getZona() {
		return this.zona;
	}

	public void setZona(Zona zona) {
		this.zona = zona;
	}

	@Column(name = "tiemporestauracion")
	public Integer getTiemporestauracion() {
		return this.tiemporestauracion;
	}

	public void setTiemporestauracion(Integer tiemporestauracion) {
		this.tiemporestauracion = tiemporestauracion;
	}

	@Column(name = "llamar")
	public Boolean getLlamar() {
		return this.llamar;
	}

	public void setLlamar(Boolean llamar) {
		this.llamar = llamar;
	}

	@Column(name = "visitble")
	public Boolean getVisitble() {
		return this.visitble;
	}

	public void setVisitble(Boolean visitble) {
		this.visitble = visitble;
	}

}
